[package]
name = "cfg"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
bit-set = "0.8.0"
bumpalo = { version = "3.17.0", features = ["collections"] }
comfy-table = "7.1.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
regex = "1.11.1"

