package plugins:main;

interface imports {
  use types.{embedding, structure, model, model-type, embedding-db, node, page};
  
  store: func(key: list<u8>, value: list<u8>);

  load: func(key: list<u8>) -> list<u8>;

  unload: func(key: list<u8>);

  log-to-user: func(information: string);
}

interface types {
  record header {
    key: string,
    value: string,
  }

  get-request: func(url: string, headers: list<header>) -> string;

  enum browser-mode {
    headless,
    headfull,
  }

  resource page {
    constructor(mode: browser-mode, url: string);
    find-in-current-page: func(selector: string) -> node;
    screenshot-browser: func() -> list<u8>;
    html: func() -> string;
  }

  resource node {
    get-element-text: func() -> string;
    click-element: func();
    type-into-element: func(keys: string);
    get-element-outer-html: func() -> string;
    screenshot-element: func() -> list<u8>;
    find-child-of-element: func(selector: string) -> node;
  }

  resource embedding-db {
    constructor(embeddings: list<embedding>, documents: list<string>);
    add-embedding: func(embedding: embedding, documents: string);
    find-closest-documents: func(search: embedding, count: u32) -> list<string>;
  }

  resource model {
    constructor(ty: model-type);
    model-downloaded: static func(ty: model-type) -> bool;
    infer: func(input: string, max-tokens: option<u32>, stop-on: option<string>) -> string;
    infer-structured: func(input: string, structure: structure) -> string;
  }

  resource embedding-model {
    constructor(ty: embedding-model-type);
    model-downloaded: static func(ty: embedding-model-type) -> bool;
    get-embedding: func(document: string) -> embedding;
  }

  resource structure {
    num: static func(num: number-parameters) -> structure;
    literal: static func(literal: string) -> structure;
    or: static func(or: either-structure) -> structure;
    then: static func(then: then-structure) -> structure;
  }

  record embedding {
    vector: list<float32>
  }

  record then-structure {
    first: structure,
    second: structure,
  }

  record either-structure {
    first: structure,
    second: structure,
  }

  record sequence-parameters {
    item: structure,
    separator: structure,
    min-len: u64,
    max-len: u64,
  }

  record number-parameters {
    min: float64,
    max: float64,
    integer: bool
  }

  record unsigned-range {
    min: u64,
    max: u64,
  }

  variant primitive-value {
    model(model),
    embedding-model(embedding-model),
    model-type(model-type),
    embedding-model-type(embedding-model-type),
    database(embedding-db),
    number(s64),
    text(string),
    file(string),
    folder(string),
    embedding(embedding),
    boolean(bool),
    page(page),
    node(node)
  }

  variant value-type {
    single(primitive-value-type),
    many(primitive-value-type),
  }

  enum primitive-value-type {
    number,
    text,
    file,
    folder,
    embedding,
    database,
    model,
    embedding-model,
    model-type,
    embedding-model-type,
    boolean,
    page,
    node,
    any
  }

  record definition {
    name: string,
    description: string,
    inputs: list<io-definition>,
    outputs: list<io-definition>,
    examples: list<example>
  }

  record example {
    name: string,
    inputs: list<input>,
    outputs: list<output>,
  }

  record io-definition {
    name: string,
    ty: value-type,
  }

  variant input {
    single(primitive-value),
    many(list<primitive-value>),
  }

  variant output {
    single(primitive-value),
    many(list<primitive-value>),
    halt,
  }

  variant model-type { MPT(mpt-type), gpt-neo-x(gpt-neo-x-type), llama(llama-type), phi, mistral }
  variant embedding-model-type { MPT(mpt-type), gpt-neo-x(gpt-neo-x-type), llama(llama-type), bert }
  enum llama-type { vicuna, guanaco, wizardlm, orca, llama-seven-chat, llama-thirteen-chat }
  enum mpt-type { base, story, instruct, chat }
  enum gpt-neo-x-type { large-pythia, tiny-pythia, dolly-seven-b, stablelm }
}

interface definitions {
  use types.{definition, input, output};

  structure: func() -> definition;

  run: func(inputs: list<input>) -> list<output>;
}

world exports {
  import imports;
  import types;
}

world plugin-world {
  export definitions;
  import imports;
  import types;
}

world both {
  import imports;
  export definitions;
}
