package plugins:main;

interface imports {

  store: func(key: list<u8>, value: list<u8>);

  load: func(key: list<u8>) -> list<u8>;

  unload: func(key: list<u8>);

  log-to-user: func(information: string);
}

interface types {
  record header {
    key: string,
    value: string,
  }

  get-request: func(url: string, headers: list<header>) -> string;

  enum browser-mode {
    headless,
    headfull,
  }

  record page-resource {
    id: u64,
    owned: bool,
  }
  drop-page: func(page: page-resource);
  create-page: func(mode: browser-mode, url: string) -> page-resource;
  find-in-current-page: func(page: page-resource, selector: string) -> node-resource;
  screenshot-browser: func(page: page-resource) -> list<u8>;
  page-html: func(page: page-resource) -> string;
  
  record node-resource {
    id: u64,
    owned: bool,
  }
  drop-node: func(node: node-resource);
  get-element-text: func(node: node-resource) -> string;
  click-element: func(node: node-resource);
  type-into-element: func(node: node-resource, keys: string);
  get-element-outer-html: func(node: node-resource) -> string;
  screenshot-element: func(node: node-resource) -> list<u8>;
  find-child-of-element: func(node: node-resource, selector: string) -> node-resource;

  record embedding-db-resource {
    id: u64,
    owned: bool,
  }
  create-embedding-db: func(embeddings: list<embedding>, documents: list<string>) -> embedding-db-resource;
  drop-embedding-db: func(model: embedding-db-resource);
  add-embedding: func(db: embedding-db-resource, embedding: embedding, documents: string);
  find-closest-documents: func(db: embedding-db-resource, search: embedding, count: u32) -> list<string>;

  record text-generation-model-resource {
    id: u64,
    owned: bool,
  }
  create-model: func(ty: model-type) -> text-generation-model-resource;
  drop-model: func(model: text-generation-model-resource);
  text-generation-model-downloaded: func(ty: model-type) -> bool;
  infer: func(model: text-generation-model-resource, input: string, max-tokens: option<u32>, stop-on: option<string>) -> string;
  infer-structured: func(model: text-generation-model-resource, input: string, regex: string) -> string;

  record embedding-model-resource {
    id: u64,
    owned: bool,
  }
  create-embedding-model: func(ty: embedding-model-type) -> embedding-model-resource;
  drop-embedding-model: func(model: embedding-model-resource);
  embedding-model-downloaded: func(ty: embedding-model-type) -> bool;
  get-embedding: func(model: embedding-model-resource, document: string) -> embedding;

  record embedding {
    vector: list<float32>
  }

  variant primitive-value {
    model(text-generation-model-resource),
    embedding-model(embedding-model-resource),
    model-type(model-type),
    embedding-model-type(embedding-model-type),
    database(embedding-db-resource),
    number(s64),
    float(f64),
    text(string),
    file(string),
    folder(string),
    embedding(embedding),
    boolean(bool),
    page(page-resource),
    node(node-resource)
  }
  
  variant value-type {
    single(primitive-value-type),
    many(primitive-value-type),
  }

  enum primitive-value-type {
    number,
    float,
    text,
    file,
    folder,
    embedding,
    database,
    model,
    embedding-model,
    model-type,
    embedding-model-type,
    boolean,
    page,
    node,
    any
  }

  record definition {
    name: string,
    description: string,
    inputs: list<io-definition>,
    outputs: list<io-definition>,
    examples: list<example>
  }

  record example {
    name: string,
    inputs: list<list<primitive-value>>,
    outputs: list<list<primitive-value>>,
  }

  record io-definition {
    name: string,
    ty: value-type,
  }

  variant model-type {
    mistral-seven,
    mistral-seven-instruct,
    mistral-seven-instruct-two,
    zephyr-seven-alpha,
    zephyr-seven-beta,
    open-chat-seven,
    starling-seven-alpha,
    tiny-llama-chat,
    tiny-llama,
    llama-seven,
    llama-thirteen,
    llama-seventy,
    llama-seven-chat,
    llama-thirteen-chat,
    llama-seventy-chat,
    llama-seven-code,
    llama-thirteen-code,
    llama-thirty-four-code,
    solar-ten,
    solar-ten-instruct,
    phi-three
  }
  variant embedding-model-type { bert }
}

interface definitions {
  use types.{definition, primitive-value};

  structure: func() -> definition;

  run: func(inputs: list<list<primitive-value>>) -> list<list<primitive-value>>;
}

world exports {
  import imports;
  import types;
}

world plugin-world {
  export definitions;
  import imports;
  import types;
}

world both {
  import imports;
  export definitions;
}
