[package]
name = "rbert"
version = "0.4.0"
edition = "2021"
description = "A simple interface for Bert embeddings "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
keywords = ["ai", "llm", "bert", "nlp", "transformers"]

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
tokenizers = { workspace = true }
thiserror.workspace = true

accelerate-src = { version = "0.3.2", optional = true }
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"], optional = true }
cudarc = { version = "0.9.14", features = ["f16"], optional = true }
half = { version = "2.3.1", features = ["num-traits", "use-intrinsics", "rand_distr"], optional = true }

tracing = "0.1.37"
serde_json = "1.0.106"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.33.0", features = ["rt"] }

kalosm-common = { workspace = true }
kalosm-model-types.workspace = true
kalosm-language-model.workspace = true
metal = { version = "0.27.0", features = ["mps"], optional = true }

[dev-dependencies]
kalosm = { workspace = true, features = ["language"], default-features = true }
anyhow.workspace = true
postcard = { version = "1.0.8", features = ["use-std"] }

[features]
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
cudnn = ["candle-core/cudnn"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]
nccl = ["cuda", "cudarc/nccl", "dep:half"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal", "dep:metal", "kalosm-common/metal"]
