[application]
name = "fusor-webgpu-runner"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Fusor WebGPU Lab"

[web.wasm_opt]
debug = false

[web.watcher]
reload_html = true
watch_path = ["src", "assets", "Cargo.toml"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
