[package]
name = "rwhisper"
version = "0.4.1"
edition = "2021"
description = "A simple interface for Whisper transcription models in Rust"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
keywords = ["ai", "whisper", "transcription"]

[dependencies]
cpal = "0.15.1"
rand.workspace = true
fusor = { path = "../../fusor/fusor", default-features = false }
fusor-gguf = { path = "../../fusor/fusor-gguf" }
byteorder = "1.4.3"
tokenizers = { workspace = true, features = ["fancy-regex"] }
serde_json = "1.0.107"
hound = "3.5"
rodio = "0.20.1"
futures-channel = { workspace = true }
tracing = "0.1.37"
futures-util = { workspace = true }
thiserror.workspace = true

half = { version = "2.3.1", features = ["num-traits", "use-intrinsics", "rand_distr"] }
kalosm-common = { workspace = true }
kalosm-model-types.workspace = true
serde = { version = "1.0.209" }
flate2 = "1.0.35"
pollster = "0.4"
rustfft = "6.4.1"

[features]
default = ["cpu", "gpu"]
cpu = ["fusor/cpu"]
gpu = ["fusor/gpu"]

[dev-dependencies]
kalosm = { workspace = true, features = ["sound", "sound-source"], default-features = true }
anyhow.workspace = true
tracing-subscriber = "0.3.19"
reqwest = { version = "0.12.15", features = ["blocking"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
