package plugins:main

interface imports {
  use types.{embedding, json-structure, structure-id, model-id, embedding-db-id}

  load-model: func(ty: model-type) -> model-id
  unload-model: func(id: model-id)
  infer: func(id: model-id, input: string, max-tokens: option<u32>, stop-on: option<string>) -> string
  infer-structured: func(id: model-id, input: string, max-tokens: option<u32>, structure: structure-id) -> string

  get-embedding: func(id: model-id, document: string) -> embedding

  create-embedding-db: func(embeddings: list<embedding>, documents: list<string>) -> embedding-db-id
  remove-embedding-db: func(id: embedding-db-id)
  find-closest-documents: func(id: embedding-db-id, search: embedding, count: u32) -> list<string>
  find-documents-within: func(id: embedding-db-id, search: embedding, within: float32) -> list<string>

  print: func(str: string)

  variant model-type { MPT(mpt-type), gpt-neo-x(gpt-neo-x-type), llama(llama-type) }
  enum llama-type { vicuna, guanaco, wizardlm }
  enum mpt-type { base, story, instruct, chat }
  enum gpt-neo-x-type { large-pythia, tiny-pythia, dolly-seven-b, stablelm }

  create-json-structure: func(structure: json-structure) -> structure-id
  remove-json-structure: func(id: structure-id)
}

interface types {
  record embedding {
    vector: list<float32>
  }

  variant json-structure {
    sequence(structure-id),
    map(json-structure-map),
    num,
    str,
    boolean,
    either(json-structure-either),
  }

  record json-structure-either {
    first: structure-id,
    second: structure-id,
  }

  record json-structure-map {
    items: list<json-kv-pair>
  }

  record json-kv-pair {
    key: string,
    value: structure-id,
  }

  record structure-id {
    id: u32
  }

  record embedding-db-id {
    id: u32,
  }

  record model-id {
    id: u32,
  }
}

interface definitions {
  use types.{embedding, model-id, embedding-db-id}

  record definition {
    name: string,
    description: string,
    inputs: list<io-definition>,
    outputs: list<io-definition>,
  }

  record io-definition {
    name: string,
    ty: value-type,
  }

  variant value {
    single(primitive-value),
    many(list<primitive-value>),
  }

  variant primitive-value {
    model(model-id),
    database(embedding-db-id),
    text(string),
    embedding(embedding),
  }

  variant value-type {
    single(primitive-value-type),
    many(primitive-value-type),
  }

  enum primitive-value-type {
    text,
    embedding,
    database,
    model,
  }

  structure: func() -> definition

  run: func(inputs: list<value>) -> list<value>
}

world plugin-world {
  import imports
  export definitions
}