cd interfaces/kalosm-sample
cargo publish
cd ../../
cd interfaces/kalosm-streams
cargo publish
cd ../../
cd interfaces/language-model
cargo publish
cd ../../
cd models/kalosm-llama
cargo publish
cd ../../
cd models/kalosm-ocr
cargo publish
cd ../../
cd models/rbert
cargo publish
cd ../../
cd models/rwhisper
cargo publish
cd ../../
cd models/rwuerstchen
cargo publish
cd ../../
cd models/segment-anything-rs
cargo publish
cd ../../
cd interfaces/kalosm-vision
cargo publish
cd ../../
cd interfaces/kalosm-sound
cargo publish
cd ../../
cd interfaces/kalosm-learning-macro
cargo publish
cd ../../
cd interfaces/kalosm-learning
cargo publish
cd ../../
cd interfaces/kalosm-language
cargo publish
cd ../../
cd interfaces/kalosm
cargo publish