on: [pull_request]
name: benchmark fusor pull requests
jobs:
  runBenchmark:
    if: github.event.pull_request.draft == false
    name: run benchmark
    runs-on: macos-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
      - uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "fusor-ml/core"
          benchName: "qmatmul"
          branchName: ${{ github.base_ref }}